// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { hasSupabaseConfig, supabase } from "./client";
import { getLocalAuthToken } from "@/lib/local-auth";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const localToken = getLocalAuthToken();
    if (localToken) {
      return next({
        headers: { Authorization: `Bearer ${localToken}` },
      });
    }

    if (hasSupabaseConfig()) {
      const { data } = await supabase.auth.getSession();
      const token = data.session?.access_token;
      if (token) {
        return next({
          headers: { Authorization: `Bearer ${token}` },
        });
      }
    }

    return next({ headers: {} });
  },
);
