// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { isLocalAuthToken } from "@/lib/auth-mode";
import {
  isServerLocalAuthMode,
  localAuthServerContext,
} from "@/lib/auth-mode.server";
import {
  getSupabaseServerEnv,
  hasSupabaseServerConfig,
} from "@/lib/supabase-env.server";

export type AuthContext = {
  localMode: boolean;
  userId: string;
  supabase: SupabaseClient<Database> | null;
  claims: { sub: string };
};

function readBearerToken(request: Request) {
  const authHeader = request.headers.get("authorization");
  if (!authHeader?.startsWith("Bearer ")) return null;
  const token = authHeader.slice(7).trim();
  return token || null;
}

export const requireSupabaseAuth = createMiddleware({
  type: "function",
}).server(async ({ next }) => {
  const request = getRequest();

  if (!request?.headers) {
    if (isServerLocalAuthMode()) {
      return next({ context: localAuthServerContext() });
    }
    throw new Error("Unauthorized: No request headers available");
  }

  const token = readBearerToken(request);

  if (!token) {
    if (isServerLocalAuthMode()) {
      return next({ context: localAuthServerContext() });
    }
    throw new Error("Unauthorized: No authorization header provided");
  }

  if (isLocalAuthToken(token)) {
    return next({ context: localAuthServerContext() });
  }

  if (!hasSupabaseServerConfig()) {
    if (isServerLocalAuthMode()) {
      return next({ context: localAuthServerContext() });
    }
    throw new Error("Unauthorized: Supabase is not configured");
  }

  const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } =
    getSupabaseServerEnv();

  const supabase = createClient<Database>(
    SUPABASE_URL!,
    SUPABASE_PUBLISHABLE_KEY!,
    {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    },
  );

  const { data, error } = await supabase.auth.getUser(token);
  if (error || !data.user) {
    if (isServerLocalAuthMode()) {
      return next({ context: localAuthServerContext() });
    }
    throw new Error(error?.message ?? "Unauthorized: Invalid token");
  }

  const context: AuthContext = {
    localMode: false,
    supabase,
    userId: data.user.id,
    claims: { sub: data.user.id },
  };

  return next({ context });
});
